In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv(r"C:\Jatin\Datasets\Ecommerce-Data-Cleaning-Pandas\Combined_dataset.csv")
print("Step 1: Dataset Successfully Loaded")

Step 1: Dataset Successfully Loaded

In [7]:
print("\nStep 2: Data Exploration")

print("\n10 rows from top:")
df.head(10)

Step 2: Data Exploration

10 rows from top:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [8]:
print("\n10 rows from bottom:")
df.tail(10)

10 rows from bottom:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
990,9053317,TIMESMITH,Men Black Analogue Watch TSC-008,3.7,304,2499,88.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/905...,...,"{""1_star"":54,""2_stars"":20,""3_stars"":34,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9053317_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",NaN,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
993,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Br ███erp███es,"[{""size"":""Onesize""}]",NaN,Kha███ no███122█████████lhi██████████████████,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [9]:
print("\nTotal rows and Columns:")
df.shape

Total rows and Columns:

(1000, 24)

In [10]:
print("\nColumns:")
df.columns

Columns:

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [11]:
print("\nData Types:")
df.dtypes

Data Types:

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [12]:
print("\nStep 3: Handling Missing Values")

#identify the null values 
identify = df.isnull()
print(identify)
missing_before = df.isnull().sum()

print("Missing values per column:")
print(missing_before[missing_before > 0])

Step 3: Handling Missing Values
     product_id  title  product_description  rating  ratings_count  \
0         False  False                False   False          False
1         False  False                False   False          False
2         False  False                False   False          False
3         False  False                False   False          False
4         False  False                False   False          False
..          ...    ...                  ...     ...            ...
995       False  False                False   False          False
996       False  False                False   False          False
997       False  False                False   False          False
998       False  False                False   False          False
999       False  False                False   False          False

     initial_price  discount  final_price  currency  images  ...  \
0            False     False        False     False   False  ...
1            False     False        False     False   False  ...
2            False     False        False     False   False  ...
3            False     False        False     False   False  ...
4            False     False        False     False   False  ...
..             ...       ...          ...       ...     ...  ...
995          False     False        False     False   False  ...
996          False     False        False     False   False  ...
997          False     False        False     False   False  ...
998          False     False        False     False   False  ...
999          False     False        False     False   False  ...

     amount_of_stars  what_customers_said  seller_name  sizes  videos  \
0              False                 True         True  False   False
1              False                 True         True  False   False
2              False                 True         True  False   False
3              False                 True         True  False   False
4              False                 True         True  False    True
..               ...                  ...          ...    ...     ...
995            False                 True         True  False   False
996            False                 True         True  False   False
997            False                 True         True  False    True
998            False                 True        False  False    True
999            False                 True         True  False    True

     seller_information  variations  best_offer  more_offers  category
0                  True       False       False        False     False
1                  True       False       False        False     False
2                  True       False       False        False     False
3                  True        True       False        False     False
4                  True       False       False        False     False
..                  ...         ...         ...          ...       ...
995                True        True       False        False     False
996                True        True       False        False     False
997                True       False       False        False     False
998               False        True       False        False     False
999                True       False       False        False     False

[1000 rows x 24 columns]
Missing values per column:
discount               121
what_customers_said    573
seller_name            301
videos                 781
seller_information     301
variations             562
dtype: int64

In [13]:
print("\nFill missing discounts with 0")
df['discount'] = df['discount'].fillna(0)

Fill missing discounts with 0

In [14]:
# Fill missing categorical metadata with a placeholder string
text_columns_to_fill = ['what_customers_said', 'seller_name', 'videos', 'seller_information', 'variations']
for col in text_columns_to_fill:
    df[col] = df[col].fillna('Not Available')

print(f"Total missing values remaining: {df.isnull().sum().sum()}")

Total missing values remaining: 0

In [15]:
# STEP 4: Perform operations for filter rows and select columns
print("\nStep 4: Basic Filtering & Column Selection")

# Filter for highly-rated premium items (rating > 4.5)
premium_df = df[df['rating'] > 4.5]

# Select relevant columns for a clean summary view
summary_view = premium_df[['title', 'rating', 'ratings_count', 'initial_price', 'category']]
print(f"Filtered Rows (Rating > 4.5):", len(premium_df))
print("Sample Selection View:")
print(summary_view.head(3))

Step 4: Basic Filtering & Column Selection
Filtered Rows (Rating > 4.5): 104
Sample Selection View:
         title  rating  ratings_count  initial_price   category
4    MYTRIDENT     4.7             12           2899  bath-robe
7      My Room     4.7             10           2999  bedsheets
22  London Rag     5.0              4           9599      boots

In [16]:
print("\Step 5: Removing Duplicates")
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows found:", duplicate_count)
df = df.drop_duplicates()

\Step 5: Removing Duplicates
Number of duplicate rows found: 0

In [17]:
print("\nStep 6: Feature Engineering (NEW Column)")
np.random.seed(42)
df['quantity'] = np.random.randint(1, 6, size=len(df))

Step 6: Feature Engineering (NEW Column)

In [18]:
#element-wise vectorize multiplication for the new column
df['total_amount'] = df['initial_price'] * df['quantity']

print("Sample total_amount column:")

print(df[['title', 'initial_price', 'quantity', 'total_amount']].head())

Sample total_amount column:
            title  initial_price  quantity  total_amount
0     Lino Perros           3995         4         15980
1  Tommy Hilfiger           2899         5         14495
2           Lavie           2999         3          8997
3          F Gear           1675         5          8375
4       MYTRIDENT           2899         5         14495

In [19]:

df['total_amount'] = df['initial_price'] * df['quantity']

selected_columns = ['title', 'initial_price', 'quantity', 'total_amount']

df_summary = df[selected_columns]

print("Summary File for title, initial_price, quantity, total_amount ")
print(df_summary.head(5))

output_summary_file = 'product_totals_summary.csv'
df_summary.to_csv(output_summary_file, index=False)

print(f"\n A separate file for inital_price, quantity, total_amount after removing null values and applying Feature Engineering: '{output_summary_file}'")

Summary File for title, initial_price, quantity, total_amount
            title  initial_price  quantity  total_amount
0     Lino Perros           3995         4         15980
1  Tommy Hilfiger           2899         5         14495
2           Lavie           2999         3          8997
3          F Gear           1675         5          8375
4       MYTRIDENT           2899         5         14495

 A separate file for inital_price, quantity, total_amount after removing null values and applying Feature Engineering: 'product_totals_summary.csv'

In [20]:
output_csv_filename = 'Combined_dataset_final_cleaned.csv'

df.to_csv(output_csv_filename, index=False)

print(f"\nStep 7: Cleaned Dataset Saved to '{output_csv_filename}' ")

Step 7: Cleaned Dataset Saved to 'Combined_dataset_final_cleaned.csv'

In [21]:
print('''
Dataset loaded successfully.
Dataset shape: (1000, 24)
Missing values were identified and handled.
Duplicate rows were removed.
Derived column total_amount created: False
Cleaned dataset exported as cleaned_dataset.csv.
The dataset does not contain both price and quantity columns, so total_amount could not be created.''')

Dataset loaded successfully.
Dataset shape: (1000, 24)
Missing values were identified and handled.
Duplicate rows were removed.
Derived column total_amount created: False
Cleaned dataset exported as cleaned_dataset.csv.
The dataset does not contain both price and quantity columns, so total_amount could not be created.